---
pulls:
  daysUntilStale: 14
  daysUntilClose: 3
  staleLabel: stale
  markComment: >
    This pull request has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs.
