---
name: Prune

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 15 * * 3'

permissions:
  issues: write
  contents: write

jobs:
  tag:
    name: Prune Branches
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Prune stale branches
        uses: crs-k/stale-branches@v5.0.0
        with:
          days-before-stale: 7
          days-before-delete: 14
